import test from 'node:test';
import assert from 'node:assert/strict';
import {MusicTitle} from '../web/music-title.mjs';
function fixture(load,field){
  const calls=[],motion={matches:false,addEventListener(){},removeEventListener(){}},env={document:{hidden:false,addEventListener(){},removeEventListener(){}},matchMedia:()=>motion};
  const canvas={hidden:true,getContext:()=>({setTransform(){},clearRect(){},fillRect(){},fillText(){}})},text={style:{},getBoundingClientRect:()=>({width:400,height:26})};let freed=0;
  const library={catalogue:['one','two'],next:(_c,_b,last)=>last==='one'?'two':'one',create(text,name){calls.push({text,name});let n=0;return {next(){return n++<3?{symbols:[65],flags:[0],fg:[0],bg:[0]}:null;},free(){freed++;}};}};
  const effect=new MusicTitle(canvas,text,{field,environment:env,load:load || (async()=>library)});
  return {effect,calls,motion,env,canvas,text,library,freed:()=>freed};
}
const track=(title='First',artist='Artist',state='playing')=>({title,artist,state});
const tick=()=>new Promise(resolve=>setImmediate(resolve));
test('baseline, duplicate and pause do not animate; track changes play once',async()=>{const h=fixture();h.effect.update(track());h.effect.update(track());h.effect.update(track('First','Artist','paused'));await tick();assert.equal(h.calls.length,0);h.effect.update(track('Next'));await tick();assert.equal(h.calls.length,1);assert.equal(h.canvas.hidden,false);h.effect.frame(100);h.effect.frame(140);assert.equal(h.freed(),0);h.effect.frame(180);assert.equal(h.freed(),1);assert.equal(h.text.style.visibility,'visible');h.effect.update(track('Next'));assert.equal(h.calls.length,1);});
test('rapid changes finish playback and retain only the latest pending identity',async()=>{const h=fixture();h.effect.update(track());h.effect.update(track('Next'));await tick();h.effect.update(track('Skipped'));h.effect.update(track('Latest'));assert.equal(h.text.style.visibility,'visible');assert.equal(h.freed(),0);for(const t of [100,140,180])h.effect.frame(t);await tick();assert.deepEqual(h.calls.map(x=>x.text),['Next','Latest']);assert.notEqual(h.calls[0].name,h.calls[1].name);});
test('stale source cancels and recovery creates a new baseline',async()=>{const h=fixture();h.effect.update(track());h.effect.update(track('Next'));await tick();h.effect.update(null);assert.equal(h.freed(),1);h.effect.update(track('Recovered'));await tick();assert.equal(h.calls.length,1);assert.equal(h.canvas.hidden,true);});
test('hidden and reduced-motion transitions release sessions and do not replay',async()=>{for(const guard of ['hidden','reduced']){const h=fixture();h.effect.update(track());h.effect.update(track('Next'));await tick();if(guard==='hidden')h.env.document.hidden=true;else h.motion.matches=true;h.effect.frame(100);assert.equal(h.freed(),1);h.env.document.hidden=false;h.motion.matches=false;h.effect.update(track('Current'));await tick();assert.equal(h.calls.length,1);}});
test('failed loading retains text without retrying duplicate samples',async()=>{const h=fixture(async()=>{throw Error('load');});h.effect.update(track());h.effect.update(track('Next'));await tick();assert.equal(h.canvas.hidden,true);assert.equal(h.text.style.visibility,'visible');h.effect.update(track('Next'));assert.equal(h.effect.loading,false);});
test('in-flight load cannot revive an expired source',async()=>{let resolve;const h=fixture(()=>new Promise(r=>resolve=r));h.effect.update(track());h.effect.update(track('Next'));h.effect.update(null);resolve(h.library);await tick();assert.equal(h.calls.length,0);assert.equal(h.canvas.hidden,true);});
test('artist changes count as identity changes; title is bounded before WASM',async()=>{const h=fixture();h.effect.update(track());h.effect.update(track('First','Other artist'));await tick();assert.equal(h.calls.length,1);h.effect.cancel();h.effect.update(track('x'.repeat(400)));await tick();assert.equal(h.calls.at(-1).text.length,110);h.effect.dispose();assert.equal(h.canvas.hidden,true);});

test('artist renderer uses artist text and responds when only song changes',async()=>{const h=fixture(null,'artist');h.effect.update(track('First','Same artist'));h.effect.update(track('Second','Same artist'));await tick();assert.equal(h.calls.length,1);assert.equal(h.calls[0].text,'Same artist');h.effect.update(null);assert.equal(h.canvas.hidden,true);assert.equal(h.text.style.visibility,'visible');});

test('manual activation replays current text with a different effect and never interrupts playback',async()=>{const h=fixture();h.effect.update(track());h.effect.activate();await tick();assert.equal(h.calls.length,1);h.effect.activate();assert.equal(h.calls.length,1);for(const t of [100,140,180])h.effect.frame(t);h.effect.activate();await tick();assert.equal(h.calls.length,2);assert.notEqual(h.calls[0].name,h.calls[1].name);h.effect.update(null);h.effect.activate();await tick();assert.equal(h.calls.length,2);});
