import test from 'node:test';import assert from 'node:assert/strict';import {TitleMark,TITLE_ROWS,TITLE_TEXT,titleColour} from '../web/title.mjs';
function fixture(reduced=false,load){let created=0,freed=0;const env={performance:{now:()=>0},document:{hidden:false},matchMedia:()=>({matches:reduced}),devicePixelRatio:3};const canvas={getBoundingClientRect:()=>({width:150,height:40}),getContext:()=>({setTransform(){},clearRect(){},fillRect(){},fillText(){}})};const library={catalogue:['a','b'],next:()=> 'a',createTitle(){created++;let count=0;return {next:()=>count++<3?{symbols:[],flags:[],fg:[]}:null,free(){freed++;}};}};return {mark:new TitleMark(canvas,{environment:env,load:load || (async()=>library)}),env,canvas,created:()=>created,freed:()=>freed,library};}
test('title is the bounded eight-row Rich glyph atlas',()=>{assert.equal(TITLE_ROWS.length,8);assert.ok(TITLE_ROWS.every(r=>Array.from(r).length===Array.from(TITLE_ROWS[0]).length));assert.ok(Array.from(TITLE_ROWS[0]).length<=60);assert.equal(TITLE_TEXT.split('\n').length,8);const f=fixture();assert.equal(f.canvas.width,300);});
test('minute schedule waits initially, ignores clicks during playback and completes',async()=>{const f=fixture();f.mark.frame(59999);assert.equal(f.created(),0);f.mark.frame(60040);await Promise.resolve();assert.equal(f.created(),1);await f.mark.trigger();assert.equal(f.created(),1);for(let t=60100;t<60300;t+=40)f.mark.frame(t);assert.equal(f.freed(),1);assert.equal(f.mark.session,null);assert.equal(f.mark.nextAt,120040);f.mark.frame(120040);await Promise.resolve();assert.equal(f.created(),2);});
test('hidden/reduced views cancel and do not replay a missed schedule',async()=>{for(const reduced of [false,true]){const f=fixture(reduced);f.env.document.hidden=!reduced;f.mark.frame(90000);await f.mark.trigger();assert.equal(f.created(),0);f.env.document.hidden=false;f.mark.motion.matches=false;f.mark.frame(90040);assert.equal(f.created(),0);}});
test('async load cancelled by hidden frame cannot revive on return',async()=>{let resolve;const pending=new Promise(r=>resolve=r),f=fixture(false,()=>pending);const loading=f.mark.trigger();f.env.document.hidden=true;f.mark.frame(1000);f.env.document.hidden=false;resolve(f.library);await loading;assert.equal(f.created(),0);});
test('load failure remains static and waits before retry; dispose frees an active session',async()=>{const f=fixture(false,async()=>{throw Error();});await f.mark.trigger();assert.equal(f.mark.session,null);assert.equal(f.mark.nextAt,60000);const other=fixture();await other.mark.trigger();other.mark.dispose();assert.equal(other.freed(),1);await other.mark.trigger();assert.equal(other.created(),1);});

test('native cell flags preserve background, inverse, dim, type styles and decorations',()=>{const f=fixture(),draws=[];f.mark.ctx={clearRect(){},fillRect(...args){draws.push({kind:'rect',args,colour:this.fillStyle,alpha:this.globalAlpha});},fillText(...args){draws.push({kind:'text',args,colour:this.fillStyle,font:this.font,alpha:this.globalAlpha});}};f.mark.cells={symbols:[65,66,32],fg:[0,0,0],bg:[0,0,0],flags:[1|2|4|8|16|64,32,16]};f.mark.draw();const glyph=draws.find(d=>d.kind==='text');assert.equal(glyph.args[0],'A');assert.ok(glyph.font.startsWith('italic bold '));assert.equal(glyph.alpha,.55);assert.equal(glyph.colour,f.mark.palette.background);assert.equal(draws.filter(d=>d.kind==='text').length,1);assert.equal(draws.filter(d=>d.kind==='rect').length,4);assert.equal(draws[0].colour,f.mark.palette.foreground);});

test('fixed native ink maps to the current theme and preserves intensity',()=>{const f=fixture();f.mark.update({green:'#224466',blue:'#112233',cyan:'#334455',yellow:'#556677',foreground:'#ddeeff'});assert.equal(titleColour(0,f.mark.palette.foreground,f.mark.palette),'#ddeeff');assert.equal(titleColour(0xff224466,'',f.mark.palette),'rgb(34,68,102)');assert.notEqual(titleColour(0xff00ff00,'',f.mark.palette),'rgb(0,255,0)');});
