const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function harness(reduced=false,render=false,loadModule=null){
  const nodes=new Map();
  function element(tag='div'){return {tagName:tag.toUpperCase(),children:[],calls:[],style:{setProperty(k,v){this[k]=v;}},dataset:{},textContent:'',hidden:false,append(...items){this.children.push(...items);},addEventListener(name,fn){this['on'+name]=fn;},setAttribute(name,v){this[name]=v;},getBoundingClientRect(){return {left:0,top:0,width:1200,height:20};},getContext(){return render?{setTransform(){},clearRect(){},fillRect(){},fillText:(...args)=>this.calls.push(args)}:null;}};}
  const get=id=>{if(!nodes.has(id))nodes.set(id,element());return nodes.get(id);};
  const c=vm.createContext({document:{getElementById:get,createElement:element,documentElement:element()},getComputedStyle:()=>({fontSize:'12px'}),matchMedia:()=>({matches:reduced}),loadEffectsModule:loadModule,performance:{now:()=>100},Date:class extends Date{},Map,innerWidth:1280,innerHeight:720,devicePixelRatio:1,addEventListener(){},requestAnimationFrame(){},setInterval(){},setTimeout(){},AbortSignal,fetch:()=>new Promise(()=>{})});
  vm.runInContext(loadModule?fs.readFileSync('web/app.js','utf8').replace("import('./effects.mjs')",'loadEffectsModule()'):fs.readFileSync('web/app.js','utf8'),c);return {run:s=>vm.runInContext(s,c),get};
}
const setup=`const data={profile:'work',interval:5,theme:{name:'Test',colours:{}},hosts:[{id:'host',label:'Host',online:true,sampled_at:100,agents:[{id:'a',host:'host',project:'test',title:'Task',harness:'qwen',status:'idle'}]}]};observe(data,100000);`;
test('baseline and duplicate polls never create milestones',()=>{const h=harness();h.run(setup);h.run('observe(data,101000);data.hosts[0].agents[0].technical={revision:5};observe(data,102000)');assert.equal(h.run('records.length'),1);});
test('work, input and completion each produce one observation',()=>{const h=harness();h.run(setup);for(const status of ['working','blocked','done'])h.run(`data.hosts[0].agents[0].status='${status}';observe(data,101000);observe(data,102000)`);assert.equal(h.run('records.slice(1).map(r=>r.kind).join()'),'Working,Blocked,Done');});
test('expired host drops agents without claiming completion and recovers once',()=>{const h=harness();h.run(setup);h.run('reconcile(126000);reconcile(127000)');assert.equal(h.run('agents.length'),0);assert.equal(h.run('records.at(-1).kind'),'LOST');h.run('data.hosts[0].sampled_at=128;observe(data,128000)');assert.equal(h.run('records.at(-1).kind'),'LINK');});
test('transport failure is deduplicated and recovery does not replay missed work',()=>{const h=harness();h.run(setup);h.run("disconnect(101000);disconnect(102000);data.hosts[0].agents[0].status='done';observe(data,103000)");assert.equal(h.run('records.slice(1).map(r=>r.kind).join()'),'LOST,LINK');});
test('fresh pane removal is detach, not done',()=>{const h=harness();h.run(setup);h.run('data.hosts[0].agents=[];observe(data,101000)');assert.equal(h.run('records.at(-1).kind'),'DETACH');});
test('reduced motion retains milestone observations',()=>{const h=harness(true);h.run(setup);h.run("data.hosts[0].agents[0].status='working';observe(data,101000)");assert.equal(h.run('records.length'),2);});
test('bounded text and transcript use textContent, not HTML',()=>{const h=harness();h.run(setup);h.run("data.hosts[0].agents[0].title='<script>test</script>';observe(data,101000)");assert.ok(h.get('transcript').textContent.includes('<script>test</script>'));assert.equal(h.run("clean('a'.repeat(1000)).length"),160);assert.equal(h.run("clean('a\\nb')"),'a b');assert.ok(!fs.readFileSync('web/app.js','utf8').includes('innerHTML'));});

test('Omarchy accent colours the complete scene',()=>{const h=harness();h.run(setup);h.run("data.theme.colours={accent:'#ff8800'};observe(data,101000)");assert.equal(h.run('palette.cyan'),'#ff8800');assert.equal(h.run('palette.blue'),'#ff8800');});
test('manual paging starts at the visible automatic page',()=>{const h=harness();h.run(setup);h.run('agents=Array.from({length:60},()=>({}));Date.now=()=>30000');assert.equal(h.run('currentPage()'),2);h.run('manualPage=currentPage()+1');assert.equal(h.run('currentPage()'),3);});



test('stale renderer text is removed from accessible output too',()=>{const h=harness();h.run(setup);h.run("textFrames={recordId:records[0].id,key:'x',frames:[],text:'RENDERER CURRENT',sources:[{id:'host',at:100}]};animationIndex=0;Date.now=()=>101000;accessible()");assert.ok(h.get('transcript').textContent.includes('RENDERER CURRENT'));h.run('disconnect(102000)');assert.ok(!h.get('transcript').textContent.includes('RENDERER CURRENT'));});


test('fractional render ticks preserve animation timing',()=>{const h=harness();h.run(setup);h.run("textFrames={recordId:records[0].id,sources:[{id:'host',at:100}]};effectSession={next:()=>({}),free(){}};animationIndex=0;frameElapsed=0;for(let i=0;i<100;i++)advanceEffects(33.1)");assert.equal(h.run('animationIndex'),99);});

test('renderer errors and source loss release sessions and retain live state',()=>{for(const reason of ['failure','offline']){const h=harness();h.run(setup);h.run("let freed=0;effectSession={next(){throw Error()},free(){freed++}};textFrames={recordId:records[0].id,sources:[{id:'host'}]};animationIndex=0;frameElapsed=0");if(reason==='offline')h.run('disconnect()');h.run('advanceEffects(40)');assert.equal(h.run('freed'),1);assert.equal(h.run('animationIndex'),-1);}});
test('fixed effect colours follow the active palette and retain intensity',()=>{const h=harness();h.run("palette={background:'#101010',foreground:'#eeeeee',blue:'#ff8800',cyan:'#ff8800',green:'#88aa22',yellow:'#ddbb44',red:'#cc4433'}");assert.equal(h.run('themedColour(0, palette.background)'),'#101010');assert.equal(h.run('themedColour(0xffff8800, palette.foreground)'),'rgb(255,136,0)');assert.notEqual(h.run('themedColour(0xff00ff00, palette.foreground)'),'rgb(0,255,0)');});






test('routine captures and metadata changes never create CLI noise',()=>{const h=harness();h.run(setup);h.run('for(let i=1;i<20;i++){data.hosts[0].sampled_at=100+i;data.hosts[0].agents[0].technical={revision:i,state_change_seq:i,interactive_ready:i%2===0,launch_pending:i%2===1};observe(data,100000+i*1000)}');assert.equal(h.run('records.length'),1);assert.equal(h.run('agents[0].technical.revision'),19);assert.ok(!h.run('JSON.stringify(viewModel())').includes('SAMPLE'));});
test('notable events are concise, contextual and observed once',()=>{const h=harness();h.run(setup);h.run("data.hosts[0].agents[0].status='working';observe(data,101000);observe(data,102000)");assert.equal(h.run('records.length'),2);assert.equal(h.run('records.at(-1).text'),'started working');assert.equal(h.run('records.at(-1).detail'),'Task');assert.equal(h.run('records.at(-1).host'),'host');});

test('sampled telemetry changes add concise events once and preserve state',()=>{const h=harness();h.run(setup);h.run("data.hosts[0].agents[0].technical={telemetry:{seq:101000000,event:'tool-start',phase:'tool',tool:'bash',model:'model',context:40,window:100}};observe(data,101000);observe(data,102000)");assert.equal(h.run("records.filter(r=>r.kind==='TOOL').length"),1);assert.equal(h.run('agents[0].status'),'idle');assert.ok(h.run('records.at(-1).text').includes('tool started · bash'));assert.ok(h.run('telemetryBrief(agents[0],102000)').includes('ctx~40%'));assert.equal(h.run('telemetryFor(agents[0],222000)'),null);});
test('telemetry baseline and output phases do not spam the CLI',()=>{const h=harness();h.run(setup);h.run("data.hosts[0].agents[0].technical={telemetry:{seq:101000000,event:'output',phase:'output'}};observe(data,101000)");assert.equal(h.run('records.length'),1);h.run("data.hosts[0].agents[0].technical={telemetry:{seq:102000000,event:'compact-end',phase:'working'}};observe(data,102000)");assert.equal(h.run('records.at(-1).kind'),'COMPACT');});
test('Pi adapter forwards only selected metadata and never returns decisions',async()=>{
  const source=fs.readFileSync('hooks/observatory.ts','utf8').replace("import { spawn } from 'node:child_process';",'').replace('export default function','function installPi');
  const callbacks={},payloads=[];const {EventEmitter}=require('node:events');
  const context={process:{env:{HERDR_ENV:'1',HERDR_PANE_ID:'w1:p1'}},Date,setTimeout,clearTimeout,spawn(){const c=new EventEmitter();c.kill=()=>{};c.stdin=new EventEmitter();c.stdin.end=text=>{payloads.push(JSON.parse(text));queueMicrotask(()=>c.emit('close'));};return c;}};
  vm.createContext(context);vm.runInContext(source+';installPi({on:(name,fn)=>callbacks[name]=fn})',Object.assign(context,{callbacks}));
  const ctx={sessionManager:{getSessionId:()=> 'session',getSessionFile:()=>'/private/session'},model:{id:'model',contextWindow:100},getContextUsage:()=>({tokens:40})};
  assert.equal(callbacks.session_start({},ctx),undefined);
  callbacks.tool_execution_start({toolName:'bash',args:{secret:'RAW SECRET'}},ctx);
  callbacks.message_end({message:{role:'assistant',content:'RAW SECRET',usage:{input:12,output:3,cacheRead:4,cacheWrite:5}}},ctx);
  await new Promise(r=>setTimeout(r,10));
  assert.ok(!JSON.stringify(payloads).includes('RAW SECRET'));assert.equal(payloads.at(-1).cache_read,4);assert.equal(payloads.at(-1).context,40);assert.ok(payloads.every((p,i)=>!i || p.seq>payloads[i-1].seq));
});

test('Pi final-response usage survives idle and is shown with explicit scope once',()=>{const h=harness();h.run(setup);h.run("data.hosts[0].agents[0].technical={telemetry:{seq:101000000,event:'output',phase:'output',input:12,output_tokens:3,cache_read:4,cache_write:5}};observe(data,101000);data.hosts[0].agents[0].technical={telemetry:{...data.hosts[0].agents[0].technical.telemetry,seq:102000000,event:'idle',phase:'idle'}};observe(data,102000)");assert.equal(h.run("records.filter(r=>r.kind==='USAGE').length"),1);assert.ok(h.run('records.at(-1).detail').includes('last response in 12 out 3 cache R 4 W 5'));assert.ok(h.run('telemetryBrief(agents[0],102000)').includes('cache 4/5'));});

test('working row motion is independent and settled states do not animate',()=>{const h=harness();h.run(setup);h.run("Date.now=()=>100000;data.hosts[0].agents[0].status='working';observe(data,100000)");const first=h.run('threadMotion(agents[0],1000)'),other=h.run('threadMotion({...agents[0],id:"other"},1000)');assert.equal(first.moving,true);assert.notEqual(first.glyph,other.glyph);assert.equal(first.progress,undefined);assert.notEqual(h.run('threadMotion(agents[0],1000).glyph'),h.run('threadMotion(agents[0],1260).glyph'));for(const state of ['idle','done','unknown','blocked'])assert.equal(h.run(`threadMotion({...agents[0],status:'${state}'},1000).moving`),false);});
test('thread arrival highlight follows observed changes once and motion stops safely',()=>{const h=harness();h.run(setup);h.run("Date.now=()=>101000;data.hosts[0].agents[0].status='working';observe(data,101000);performance.now=()=>500;observe(data,102000)");assert.equal(h.run('rowActivity.get("a")'),100);assert.ok(h.run('threadMotion(agents[0],500).flash')>0);assert.equal(h.run('threadMotion(agents[0],2000).flash'),0);for(const guard of ['reduced.matches=true','disconnected=true','Date.now=()=>200000']){h.run('reduced.matches=false;disconnected=false;Date.now=()=>101000;'+guard);assert.equal(h.run('threadMotion(agents[0],500).moving'),false);assert.equal(h.run('threadMotion(agents[0],500).flash'),0);}});

const mockEffect=`let freed=0,captured=[];effectLibrary={catalogue:['decrypt','rain'],next:()=>lastEffect==='decrypt'?'rain':'decrypt',create(text){captured.push(text);let n=0;return {next(){return n++<3?{width:Array.from(text).length,height:1,symbols:[88],flags:[0],fg:[0],bg:[0]}:null;},free(){freed++;}};}};`;
test('fresh events alone trigger full playback, with no cooldown backlog or periodic replay',async()=>{const h=harness();h.run(setup);h.run(mockEffect);h.run('advanceEffects(500000)');assert.equal(h.run('animationIndex'),-1);h.run("data.hosts[0].agents[0].status='working';observe(data,101000)");await h.run('refreshFrames()');assert.equal(h.run('captured.length'),1);assert.equal(h.run('captured[0]'),h.run('eventLine(records.at(-1))'));h.run("data.hosts[0].agents[0].status='blocked';observe(data,102000);advanceEffects(34);advanceEffects(34)");assert.equal(h.run('animationIndex'),2);h.run('advanceEffects(34)');assert.equal(h.run('animationIndex'),-1);assert.equal(h.run('holdElapsed'),0);h.run("data.hosts[0].agents[0].status='done';observe(data,103000);advanceEffects(120000);advanceEffects(120000)");assert.equal(h.run('pendingEffect'),null);assert.equal(h.run('captured.length'),1);h.run("data.hosts[0].agents[0].status='idle';observe(data,104000)");await h.run('refreshFrames()');assert.equal(h.run('captured.length'),2);assert.equal(h.run('lastEffect'),'rain');});
test('hidden and reduced-motion arrivals never become delayed effects',async()=>{for(const guard of ['reduced.matches=true','document.hidden=true']){const h=harness();h.run(setup);h.run(mockEffect);h.run(guard+";data.hosts[0].agents[0].status='working';observe(data,101000)");h.run('reduced.matches=false;document.hidden=false;advanceEffects(500000)');await h.run('refreshFrames()');assert.equal(h.run('captured.length'),0);assert.ok(h.run('eventLine(records.at(-1))').includes('started working'));}});
test('scrolling the animated record out of view cancels it without replay',async()=>{const h=harness();h.run(setup);h.run(mockEffect);h.run("data.hosts[0].agents[0].status='working';observe(data,101000)");await h.run('refreshFrames()');h.run('for(let i=0;i<24;i++)record("INFO","later",102000);advanceEffects(34)');assert.equal(h.run('animationIndex'),-1);assert.equal(h.run('freed'),1);h.run('advanceEffects(999999)');assert.equal(h.run('captured.length'),1);});
test('renderer failure consumes the arrival and preserves the plain event',async()=>{const h=harness();h.run(setup);h.run(mockEffect);h.run("effectLibrary.create=()=>{throw Error('failed')};data.hosts[0].agents[0].status='working';observe(data,101000)");await h.run('refreshFrames()');assert.equal(h.run('animationIndex'),-1);assert.equal(h.run('pendingEffect'),null);assert.ok(h.run('viewModel().events.at(-1).line').includes('started working'));});

test('source loss cancels a pending event even after recovery',async()=>{const h=harness();h.run(setup);h.run(mockEffect);h.run("data.hosts[0].agents[0].status='blocked';observe(data,102000);disconnect(103000);observe(data,104000)");await h.run('refreshFrames()');assert.equal(h.run('captured.length'),0);});

test('in-flight WASM initialisation cannot revive a line after transient source loss or hiding',async()=>{
  for(const reason of ['source','hidden']){
    let resolveImport,created=0;
    const pendingModule=new Promise(resolve=>resolveImport=resolve);
    // Mock only the import boundary: refreshFrames still awaits its actual module/loadEffects chain.
    const h=harness(false,false,()=>pendingModule);h.run(setup);
    h.run("data.hosts[0].agents[0].status='working';observe(data,101000)");
    const loading=h.run('refreshFrames()');assert.equal(h.run('loadingFrames'),true);
    if(reason==='source')h.run('data.hosts[0].online=false;observe(data,102000);data.hosts[0].online=true;observe(data,103000)');
    else h.run('document.hidden=true');
    resolveImport({loadEffects:async()=>({catalogue:['decrypt'],create(){created++;return {next:()=>({}),free(){}};}}),nextEffect:()=> 'decrypt'});
    await loading;
    assert.equal(created,0);assert.equal(h.run('animationIndex'),-1);assert.equal(h.run('loadingFrames'),false);
    h.run('document.hidden=false;advanceEffects(999999)');assert.equal(created,0);
  }
});
test('reconciliation immediately releases an active effect on source loss',async()=>{const h=harness();h.run(setup);h.run(mockEffect);h.run("data.hosts[0].agents[0].status='working';observe(data,101000)");await h.run('refreshFrames()');h.run('data.hosts[0].online=false;observe(data,102000)');assert.equal(h.run('freed'),1);assert.equal(h.run('animationIndex'),-1);});

test('DOM cards expose native state and one honest coverage note',()=>{const h=harness();h.run(setup);h.run('Date.now=()=>101000;draw()');const card=h.run('viewModel().cards[0]');assert.equal(card.state,'Idle');assert.equal(card.pane,'a');assert.equal(card.note,'No fresh hook sample');assert.equal(card.tiles.length,0);assert.equal(h.run('cardNodes[0].state.textContent'),'Idle');assert.equal(h.run('cardNodes[0].checkout.hidden'),true);assert.equal(card.title,undefined);assert.equal(h.run('cardNodes.filter(c=>!c.card.hidden).length'),1);});
test('eight cards page with visible click controls and personal categories',()=>{const h=harness();h.run(setup);h.run('agents=Array.from({length:17},(_,i)=>({...agents[0],id:"host:w1:p"+i,project:"project"+i,category:i%2?"work":"personal"}));manualPage=0');h.get('next').onclick();assert.equal(h.run('viewModel().cards[0].project'),'project8');assert.equal(h.run('viewModel().cards.length'),8);h.run("snapshot.profile='personal';cycleCategory()");assert.equal(h.run('category'),'work');assert.ok(h.run('viewModel().cards.every(a=>Number(a.pane.slice(4))%2===1)'));});
test('fleet uses readable metric labels and suppresses stale values',()=>{const h=harness();h.run(setup);h.run('data.hosts[0].metrics={cpu_percent:25,memory:{used:5,total:10},gpu:{percent:80},disk:{used:1,total:4},rx_rate:2048,tx_rate:1024};observe(data,101000)');const host=h.run('viewModel(100,101000).hosts[0]');assert.equal(host.metrics.map(m=>m[0]).join(','),'Processor,Memory,Graphics,Storage,Network down,Network up,Sample age');assert.equal(host.metrics[0][1],'25%');h.run('reconcile(126000)');assert.equal(h.run('viewModel().hosts[0].online'),false);assert.ok(h.run('viewModel().hosts[0].metrics.every(m=>m[1]==="Unavailable")'));});
test('theme variables include backgrounds and support light palettes without local override',()=>{const h=harness();h.run(setup);h.run("data.theme={name:'Light',colours:{background:'#fafafa',foreground:'#101010',accent:'#225588'}};observe(data,101000);draw()");assert.equal(h.run("document.documentElement.style['--background']"),'#fafafa');assert.equal(h.run('document.documentElement.style.colorScheme'),'light');});
test('footer is four bounded single-line records and cards have no text effect canvas',()=>{const h=harness();h.run(setup);h.run('for(let i=0;i<80;i++)record("INFO","event "+i,101000);draw()');assert.equal(h.run('records.length'),60);assert.equal(h.run('viewModel().events.length'),4);assert.equal(h.run('eventNodes.filter(e=>!e.row.hidden).length'),4);assert.ok(h.run('cardNodes.every(c=>c.card.children.every(n=>n.tagName!=="CANVAS"))'));});
test('plain DOM line remains available while footer effect plays and failures restore it',async()=>{const h=harness(false,true);h.run(setup);h.run(mockEffect);h.run("data.hosts[0].agents[0].status='working';observe(data,101000)");await h.run('refreshFrames()');h.run('draw()');assert.equal(h.get('event-effect').hidden,false);assert.equal(h.run('eventNodes[1].text.style.visibility'),'hidden');assert.ok(h.run('eventNodes[1].text.textContent').includes('started working'));assert.equal(h.run('cardNodes[0].state.textContent'),'Working');h.run('stopEffect();draw()');assert.equal(h.get('event-effect').hidden,true);assert.equal(h.run('eventNodes[1].text.style.visibility'),'visible');});

test('total count includes mixed-state threads beyond the visible page',()=>{const h=harness();h.run(setup);h.run('agents=Array.from({length:17},(_,i)=>({...agents[0],id:"host:w1:p"+i,status:i%2?"idle":"done"}));manualPage=1;draw()');assert.equal(h.run('viewModel().total'),17);assert.equal(h.run('viewModel().cards.length'),8);assert.equal(h.get('thread-total').textContent,'17 total');});

test('offline fleet is distinguished from an empty permitted view',()=>{const h=harness();h.run(setup);h.run('data.hosts[0].online=false;observe(data,101000)');assert.equal(h.run('viewModel().connection'),'Sources unavailable');assert.ok(h.run('viewModel().empty').includes('Waiting for a source'));});

test('fleet gauges represent real bounded percentages and unknown is distinct from zero',()=>{const h=harness();h.run(setup);h.run('data.hosts[0].metrics={cpu_percent:0,memory:{used:3,total:4},gpu:{percent:55},disk:{used:1,total:2}};observe(data,101000);draw()');assert.equal(h.run('hostNodes[0].fields[0].gauge.dataset.known'),'true');assert.equal(h.run('hostNodes[0].fields[0].fill.style.width'),'0%');assert.equal(h.run('hostNodes[0].fields[1].fill.style.width'),'75%');assert.equal(h.run('hostNodes[0].fields[2].fill.style.width'),'55%');h.run('data.hosts[0].online=false;observe(data,102000);draw()');assert.equal(h.run('hostNodes[0].fields[0].gauge.dataset.known'),'false');assert.equal(h.run('hostNodes[0].fields[0].value.textContent'),'—');assert.equal(h.run('hostNodes[0].fields[4].direction.dataset.known'),'false');});
test('identity labels explain agent, pane and host; auto-paging defaults on only when needed',()=>{const h=harness();h.run(setup);h.run('draw()');assert.ok(h.run('cardNodes[0].identity.textContent').startsWith('qwen · host · a'));assert.equal(h.get('rotate').hidden,true);h.run('agents=Array.from({length:9},()=>({...agents[0]}));draw()');assert.equal(h.get('rotate').hidden,false);assert.equal(h.get('rotate').textContent,'Auto-page threads: on');h.get('next').onclick();assert.equal(h.get('rotate').textContent,'Auto-page threads: off');h.get('rotate').onclick();assert.equal(h.get('rotate').textContent,'Auto-page threads: on');});
test('effects keep internal cooldown without timer, pause button or adjustment hotkeys',()=>{const h=harness();assert.equal(h.run('holdSeconds'),120);const html=fs.readFileSync('web/index.html','utf8'),code=fs.readFileSync('web/app.js','utf8');for(const id of ['pause','cooldown','less-effects','more-effects'])assert.ok(!html.includes('id="'+id+'"'));assert.ok(!code.includes('function pause('));assert.ok(!code.includes('ArrowRight'));assert.ok(!code.includes('ArrowLeft'));});

test('music metadata expires independently and uses text content',()=>{const h=harness();h.run("Date.now=()=>101000;music={available:true,state:'playing',captured_at:100,title:'<b>Track</b>',artist:'Artist'};musicReceived=100000;draw()");assert.equal(h.get('music-title').textContent,'<b>Track</b>');assert.equal(h.get('music-widget').hidden,false);h.run('Date.now=()=>104000;draw()');assert.equal(h.get('music-widget').hidden,true);assert.equal(h.get('music-title').textContent,'');});
test('background interactions exclude cards and controls',()=>{const h=harness();assert.equal(h.run("backgroundHit({id:'threads'})"),true);assert.equal(h.run("backgroundHit({className:'thread-card'})"),false);assert.equal(h.run("backgroundHit({id:'rotate'})"),false);});

test('recent observations have semantic icons and distinct theme colours',()=>{const h=harness();h.run(setup);h.run('record("TOOL","tool started",101000);record("COMPACT","compacting context",101000);record("Done","completed",101000);draw()');assert.equal(h.run('eventNodes[1].glyph.textContent'),h.run('eventIcon("TOOL")'));assert.notEqual(h.run('eventIcon("TOOL")'),h.run('eventIcon("COMPACT")'));assert.equal(h.run('eventNodes[1].row.style.color'),h.run('palette.cyan'));assert.equal(h.run('eventNodes[2].row.style.color'),h.run('palette.yellow'));assert.equal(h.run('eventNodes[3].row.style.color'),h.run('palette.green'));});
test('background canvas ends at footer top and cannot receive footer clicks',()=>{const h=harness();h.run("document.getElementById('activity').getBoundingClientRect=()=>({top:590});let resized=0;pixelField={resize(){resized++},update(){}};fitBackground();fitBackground()");assert.equal(h.get('pixel-field').style.height,'590px');assert.equal(h.run('resized'),1);assert.equal(h.run("backgroundHit({id:'activity'})"),false);});
test('retired activity widget is absent and Rich title is an accessible button',()=>{const html=fs.readFileSync('web/index.html','utf8');assert.ok(!html.includes('Observed activity'));assert.ok(!html.includes('id="equaliser"'));assert.ok(html.includes('id="brand-title"'));assert.ok(html.includes('aria-label="Rich. Play title effect"'));});

test('state colour follows Done for a tool observation and totals cover all cards',()=>{const h=harness();h.run(setup);h.run("record('TOOL','tool finished',101000,{state:'Done'});agents=Array.from({length:10},(_,i)=>({...agents[0],status:i<3?'working':i<5?'blocked':'done'}));draw()");assert.equal(h.run('eventNodes[1].row.style.color'),h.run('palette.green'));assert.equal(h.get('working-count').textContent,3);assert.equal(h.get('blocked-count').textContent,2);assert.equal(h.get('done-count').textContent,5);});
test('Codex coverage explains absent counters while Pi tiles retain zero and unknown distinction',()=>{const h=harness();h.run(setup);h.run("Date.now=()=>101000;agents[0].harness='codex';agents[0].technical={telemetry:{seq:101000000,phase:'tool',tool:'bash',event:'tool-start'}};draw()");assert.equal(h.run('viewModel().cards[0].note'),'Waiting for reported usage');assert.equal(h.run('viewModel().cards[0].tiles.length'),0);h.run("agents[0].harness='pi';agents[0].technical.telemetry={seq:101000000,phase:'idle',event:'idle',context:40,window:100,input:0,output_tokens:12,cache_read:0};draw()");assert.equal(h.run('viewModel().cards[0].tiles.length'),3);assert.equal(h.run('viewModel().cards[0].tiles[0].ratio'),.4);assert.equal(h.run('viewModel().cards[0].tiles[2].value'),'0 / —');assert.equal(h.run('viewModel().cards[0].note'),'Partial usage coverage');h.run('Date.now=()=>222000;draw()');assert.equal(h.run('viewModel().cards[0].tiles.length'),0);});
test('subagent observations are parent-bound activity without invented roster counts',()=>{const h=harness();h.run(setup);h.run("Date.now=()=>101000;data.hosts[0].agents[0].technical={telemetry:{seq:101000000,event:'subagent-start',phase:'working'}};observe(data,101000);draw()");assert.equal(h.run('records.at(-1).kind'),'SUBAGENT');assert.equal(h.run('viewModel().cards[0].activity'),'Subagent started');assert.equal(h.run('viewModel().cards[0].state'),'Idle');assert.equal(h.run('viewModel().cards[0].subagents'),undefined);});

test('music text has an accessible equivalent independent of effect visibility',()=>{const h=harness();h.run("Date.now=()=>101000;music={available:true,state:'playing',captured_at:100,title:'Track',artist:'Artist'};musicReceived=100000;draw();document.getElementById('music-title').style.visibility='hidden'");assert.equal(h.get('music-accessible').textContent,'Track · Artist · playing');h.run('music=null;draw()');assert.equal(h.get('music-accessible').textContent,'');});

test('Working uses amber and Idle uses green under theme changes',()=>{const h=harness();h.run("palette.yellow='#cc9911';palette.green='#228844'");assert.equal(h.run("colour('Working')"),'#cc9911');assert.equal(h.run("colour('Idle')"),'#228844');assert.equal(h.run("colour('Blocked')"),h.run('palette.red'));});
test('numeric usage expires by source timestamp even if hooks stay fresh',()=>{const h=harness();h.run(setup);h.run("Date.now=()=>101000;agents[0].technical={telemetry:{seq:101000000,event:'tool-start',phase:'tool',input:12,context:20,window:100,usage_seq:100000000}};Date.now=()=>222000;agents[0].technical.telemetry.seq=222000000");assert.equal(h.run('telemetryFor(agents[0]).input'),null);assert.equal(h.run('telemetryFor(agents[0]).phase'),'tool');});
test('redundant operational labels are removed from the display',()=>{const html=fs.readFileSync('web/index.html','utf8'),source=fs.readFileSync('web/app.js','utf8');assert.ok(!html.includes('id="sampling"'));assert.ok(!source.includes('Playing on iapetus'));assert.ok(html.includes('id="artist-effect"'));});


test("idle follows Herdr done/idle green role",()=>{const h=harness();assert.equal(h.run("colour('Idle')"),h.run("palette.green"));});


test('hover details replace inspector and click is a bounded decorative pulse',()=>{const h=harness();h.run(setup);h.run('Date.now=()=>101000;draw();cardNodes[0].card.onclick();draw(100)');assert.ok(Number(h.run("cardNodes[0].card.style['--click']"))>0);h.run('draw(900)');assert.equal(h.run("cardNodes[0].card.style['--click']"),'0.000');assert.equal(h.run('records.length'),1);h.run('disconnect();draw()');assert.equal(h.run('cardNodes[0].identity.textContent'),'');const html=fs.readFileSync('web/index.html','utf8');for(const id of ['inspector','profile','theme'])assert.ok(!html.includes('id="'+id+'"'));assert.ok(html.includes('id="idle-count"'));});
test('fleet histories append measured samples once and never fabricate missing readings',()=>{const h=harness();h.run(setup);h.run('data.hosts[0].metrics={cpu_percent:0};data.hosts[0].sampled_at=101;observe(data,101000);observe(data,101100)');assert.equal(h.run("fleetHistory.get('host').rows.length"),2);assert.equal(h.run("sparkline([null,0,100])"),'·▁█');h.run('data.hosts[0].online=false;observe(data,102000)');assert.equal(h.run('fleetHistory.size'),0);});
test('bare checkout and duplicated generic working activity stay out of cards',()=>{const h=harness();h.run(setup);h.run("Date.now=()=>101000;agents[0].checkout='.bare';agents[0].status='working';agents[0].technical={telemetry:{seq:101000000,phase:'working'}};draw()");assert.equal(h.run('cardNodes[0].checkout.hidden'),true);assert.equal(h.run('cardNodes[0].activity.hidden'),true);});
test('reported session totals and compactions take precedence over last response counters',()=>{const h=harness();const view=h.run("cardTelemetry({status:'working'},{total_input:12000,total_output:300,total_cache_read:10000,total_uncached_input:2000,compactions:0})");assert.equal(view.tiles[0].label,'Session tokens');assert.equal(view.tiles[1].ratio,10000/12000);assert.equal(view.tiles[2].value,'0');});

test('hover detail keeps hook and usage-source ages separate and clears stale numeric provenance',()=>{const h=harness();h.run(setup);h.run("Date.now=()=>110000;agents[0].technical={telemetry:{seq:109000000,usage_seq:100000000,usage_source:'codex-rollout',event:'tool-start',phase:'tool',total_input:1000}};draw()");const text=h.run('cardNodes[0].identity.textContent');assert.ok(text.includes('Hook: 1s ago'));assert.ok(text.includes('Codex record · 10s ago'));h.run('Date.now=()=>221000;agents[0].technical.telemetry.seq=221000000;draw()');assert.ok(h.run('cardNodes[0].identity.textContent').includes('Usage time unknown'));assert.ok(!h.run('cardNodes[0].identity.textContent').includes('Codex record'));});
test('fleet graph labels count actual readings and missing gaps independently',()=>{const h=harness();h.run(setup);h.run('data.hosts[0].metrics={cpu_percent:0};data.hosts[0].sampled_at=101;observe(data,101000);draw()');assert.ok(h.run('hostNodes[0].fields[0].graph.title').startsWith('1 measured samples · 1 missing'));assert.ok(h.run('hostNodes[0].fields[4].graph.title').includes('0 measured samples · 2 missing · peak unavailable'));h.run('data.hosts[0].metrics={rx_rate:0};data.hosts[0].sampled_at=102;observe(data,102000);draw()');assert.ok(h.run('hostNodes[0].fields[4].graph.title').endsWith('peak 0.0 KiB/s'));});

test('hover metrics use concise exact numbers and accessible context matches the card percentage',()=>{const h=harness();h.run(setup);h.run("Date.now=()=>101000;agents[0].technical={telemetry:{seq:101000000,event:'tool-end',phase:'working',result:'finished',tool:'Bash',context:185000,window:250000,context_percent:72,total_input:21700000,total_output:48400,total_cache_read:21000000,total_uncached_input:700000,compactions:3}};draw()");const text=h.run('cardNodes[0].identity.textContent');assert.ok(text.includes('Session: 21700000 in · 48400 out'));assert.ok(text.includes('Cache: 21000000 read · 700000 uncached'));assert.ok(h.run('telemetryBrief(agents[0])').includes('ctx~72%'));assert.equal(h.run('cardNodes[0].activityText.textContent'),'Tool finished');});
test('source expiry clears measured history before a later recovery',()=>{const h=harness();h.run(setup);h.run('data.hosts[0].metrics={cpu_percent:50};data.hosts[0].sampled_at=101;observe(data,101000)');assert.ok(h.run('fleetHistory.size')>0);h.run('reconcile(127000)');assert.equal(h.run('fleetHistory.size'),0);h.run('data.hosts[0].sampled_at=128;observe(data,128000)');assert.equal(h.run("fleetHistory.get('host').rows.length"),1);});
