import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {EventEmitter} from 'node:events';
function fixture(branch){const callbacks={},payloads=[];const source=fs.readFileSync('hooks/observatory.ts','utf8').replace("import { spawn } from 'node:child_process';",'').replace('export default function','function installPi');const context={process:{env:{HERDR_ENV:'1',HERDR_PANE_ID:'w1:p1'}},Date:class extends Date{static now(){return 1000000;}},setTimeout,clearTimeout,spawn(){const child=new EventEmitter();child.kill=()=>{};child.stdin=new EventEmitter();child.stdin.end=text=>{payloads.push(JSON.parse(text));queueMicrotask(()=>child.emit('close'));};return child;},callbacks};vm.createContext(context);vm.runInContext(source+';installPi({on:(name,fn)=>callbacks[name]=fn})',context);return {callbacks,payloads,ctx:{sessionManager:{getSessionId:()=> 'session',getSessionFile:()=> '/private/session',getBranch:()=>branch},model:{id:'model',contextWindow:100},getContextUsage:()=>({tokens:20})}};}
const message=(timestamp,input=0)=>({type:'message',message:{role:'assistant',timestamp,usage:{input,output:2,cacheRead:0,cacheWrite:0},content:'PRIVATE'}});
test('Pi reload seeds only recent active-branch usage without refreshing source age',async()=>{for(const stamp of [999000,800000,1000001,undefined]){const f=fixture([message(stamp)]);f.callbacks.session_start({},f.ctx);await new Promise(r=>setTimeout(r,5));assert.equal(f.payloads[0].input,stamp===999000?0:undefined);assert.equal(f.payloads[0].usage_seq,stamp===999000?999000000:undefined);assert.ok(!JSON.stringify(f.payloads).includes('PRIVATE'));}});
test('Pi agent_end does not replace newer live usage with a lagging branch entry',async()=>{const f=fixture([message(990000,1)]);f.callbacks.session_start({},f.ctx);f.callbacks.message_end({message:message(999000,7).message},f.ctx);f.callbacks.agent_end({},f.ctx);await new Promise(r=>setTimeout(r,5));assert.equal(f.payloads.at(-1).input,7);assert.equal(f.payloads.at(-1).usage_seq,999000000);});
test('Pi branch seeding is bounded to the last 128 entries and missing API is safe',async()=>{const f=fixture([message(999000),...Array(128).fill({type:'label'})]);f.callbacks.session_start({},f.ctx);await new Promise(r=>setTimeout(r,5));assert.equal(f.payloads[0].input,undefined);delete f.ctx.sessionManager.getBranch;f.callbacks.session_start({},f.ctx);await new Promise(r=>setTimeout(r,5));assert.equal(f.payloads.at(-1).input,undefined);});

test('Pi complete session totals include cache and auxiliary usage without summing only the recent branch',async()=>{const f=fixture([]);f.ctx.sessionManager.getEntries=()=>[{type:'message',message:{role:'assistant',usage:{input:10,output:2,cacheRead:30,cacheWrite:5}}},{type:'usage',usage:{input:0,output:0,cacheRead:7,cacheWrite:0}},{type:'compaction',usage:{input:4,output:1,cacheRead:0,cacheWrite:0}}];f.callbacks.session_start({},f.ctx);await new Promise(r=>setTimeout(r,5));const p=f.payloads[0];assert.equal(p.total_input,56);assert.equal(p.total_output,3);assert.equal(p.total_cache_read,37);assert.equal(p.total_uncached_input,14);assert.equal(p.compactions,1);});
test('Pi totals remain unknown when complete bounded API coverage is unavailable',async()=>{for(const entries of [undefined,Array(4097).fill({type:'compaction'})]){const f=fixture([]);f.ctx.sessionManager.getEntries=()=>entries;f.callbacks.session_start({},f.ctx);await new Promise(r=>setTimeout(r,5));assert.equal(f.payloads[0].total_input,undefined);assert.equal(f.payloads[0].compactions,undefined);}});

test('Pi missing auxiliary usage leaves cumulative counters unknown, preserving complete compaction count',async()=>{for(const type of ['usage','compaction','branch_summary']){const f=fixture([]);f.ctx.sessionManager.getEntries=()=>[message(999000,4),{type}];f.callbacks.session_start({},f.ctx);await new Promise(r=>setTimeout(r,5));const p=f.payloads[0];assert.equal(p.total_input,null);assert.equal(p.total_output,null);assert.equal(p.total_cache_read,null);assert.equal(p.compactions,type==='compaction'?1:0);}});
