const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function harness(reduced=false,render=false){const nodes=new Map();const get=id=>{if(!nodes.has(id))nodes.set(id,{calls:[],getContext(){return render?{setTransform(){},fillRect(){},fillText:(...args)=>this.calls.push(args),save(){},restore(){},beginPath(){},rect(){},clip(){}}:null;},addEventListener(){},setAttribute(){},textContent:''});return nodes.get(id);};const c=vm.createContext({document:{getElementById:get},matchMedia:()=>({matches:reduced}),performance:{now:()=>100},Date:class extends Date{},Map,innerWidth:1280,innerHeight:720,devicePixelRatio:1,addEventListener(){},requestAnimationFrame(){},setInterval(){},setTimeout(){},AbortSignal,fetch:()=>new Promise(()=>{})});vm.runInContext(fs.readFileSync('web/app.js','utf8'),c);return {run:s=>vm.runInContext(s,c),get};}
const setup=`const data={profile:'work',interval:5,theme:{name:'Test',colours:{}},hosts:[{id:'host',label:'Host',online:true,sampled_at:100,agents:[{id:'a',host:'host',project:'test',title:'Task',harness:'qwen',status:'idle'}]}]};observe(data,100000);`;
test('baseline and duplicate polls never create milestones',()=>{const h=harness();h.run(setup);h.run('observe(data,101000);data.hosts[0].agents[0].technical={revision:5};observe(data,102000)');assert.equal(h.run('records.length'),1);});
test('work, input and completion each produce one observation',()=>{const h=harness();h.run(setup);for(const status of ['working','blocked','done'])h.run(`data.hosts[0].agents[0].status='${status}';observe(data,101000);observe(data,102000)`);assert.equal(h.run('records.slice(1).map(r=>r.kind).join()'),'EXEC,INPUT,DONE');});
test('expired host drops agents without claiming completion and recovers once',()=>{const h=harness();h.run(setup);h.run('reconcile(126000);reconcile(127000)');assert.equal(h.run('agents.length'),0);assert.equal(h.run('records.at(-1).kind'),'LOST');h.run('data.hosts[0].sampled_at=128;observe(data,128000)');assert.equal(h.run('records.at(-1).kind'),'LINK');});
test('transport failure is deduplicated and recovery does not replay missed work',()=>{const h=harness();h.run(setup);h.run("disconnect(101000);disconnect(102000);data.hosts[0].agents[0].status='done';observe(data,103000)");assert.equal(h.run('records.slice(1).map(r=>r.kind).join()'),'LOST,LINK');});
test('fresh pane removal is detach, not done',()=>{const h=harness();h.run(setup);h.run('data.hosts[0].agents=[];observe(data,101000)');assert.equal(h.run('records.at(-1).kind'),'DETACH');});
test('reduced motion retains milestone observations',()=>{const h=harness(true);h.run(setup);h.run("data.hosts[0].agents[0].status='working';observe(data,101000)");assert.equal(h.run('records.length'),2);});
test('bounded text and transcript use textContent, not HTML',()=>{const h=harness();h.run(setup);h.run("data.hosts[0].agents[0].title='<script>test</script>';observe(data,101000)");assert.ok(h.get('transcript').textContent.includes('<script>test</script>'));assert.equal(h.run("clean('a'.repeat(1000)).length"),160);assert.equal(h.run("clean('a\\nb')"),'a b');assert.ok(!fs.readFileSync('web/app.js','utf8').includes('innerHTML'));});
test('scene capacities fit both display sizes and buffers are bounded',()=>{const h=harness();for(const [w,height] of [[1280,720],[1920,1080]]){const g=h.run(`geometry(${w},${height})`);assert.ok(8+g.processRows<Math.floor((height-g.margin*2)/g.line)-10);}h.run("for(let i=0;i<100;i++)record('EXEC','test',100000)");assert.equal(h.run('records.length'),60);});

test('Omarchy accent colours the complete scene',()=>{const h=harness();h.run(setup);h.run("data.theme.colours={accent:'#ff8800'};observe(data,101000)");assert.equal(h.run('palette.cyan'),'#ff8800');assert.equal(h.run('palette.blue'),'#ff8800');});
test('manual paging starts at the visible automatic page',()=>{const h=harness();h.run(setup);h.run('agents=Array.from({length:60},()=>({}));Date.now=()=>30000');assert.equal(h.run('currentPage()'),2);h.run('manualPage=currentPage()+1');assert.equal(h.run('currentPage()'),3);});

test('fresh captures feed sampled records once while duplicate polls remain quiet',()=>{const h=harness();h.run(setup);assert.equal(h.run('feedQueue.length'),2);h.run('observe(data,101000)');assert.equal(h.run('feedQueue.length'),2);h.run('drainFeed(1000,101000)');assert.equal(h.run('records.at(-1).kind'),'SAMPLE');h.run('drainFeed(2000,101000)');assert.equal(h.run('records.at(-1).kind'),'PANE');h.run('data.hosts[0].sampled_at=105;observe(data,105000)');assert.equal(h.run('feedQueue.length'),2);});
test('queued observations disappear on disconnect or source expiry',()=>{const h=harness();h.run(setup);h.run('disconnect(101000);drainFeed(1000,101000)');assert.equal(h.run('feedQueue.length'),0);assert.equal(h.run('records.at(-1).kind'),'LOST');const fresh=harness();fresh.run(setup);fresh.run('drainFeed(1000,126000)');assert.equal(fresh.run('feedQueue.length'),0);assert.equal(fresh.run('records.length'),1);});
test('latest capture replaces backlog and reduced motion retains feed without FX',()=>{const h=harness(true);h.run(setup);h.run('data.hosts[0].sampled_at=105;observe(data,105000);drainFeed(1000,105000)');assert.equal(h.run('records.at(-1).kind'),'SAMPLE');assert.equal(h.run('feedQueue.length'),1);});

test('renderer is character-cell TUI with local WASM renderer and no decorative geometry',()=>{const code=fs.readFileSync('web/app.js','utf8');assert.ok(code.includes("import('./effects.mjs')"));assert.ok(code.includes('THREADS /'));assert.ok(code.includes('CLI FEED / TIMESTAMPED'));assert.ok(!/ttfx/i.test(code));for(const primitive of ['ctx.ellipse','ctx.arc','strokeText','fillRect(x+seed'])assert.ok(!code.includes(primitive));});

test('stale renderer text is removed from accessible output too',()=>{const h=harness();h.run(setup);h.run("textFrames={key:'x',frames:[],text:'RENDERER CURRENT',sources:[{id:'host',at:100}]};animationIndex=0;Date.now=()=>101000;accessible()");assert.ok(h.get('transcript').textContent.includes('RENDERER CURRENT'));h.run('disconnect(102000)');assert.ok(!h.get('transcript').textContent.includes('RENDERER CURRENT'));});

test('complete playback cannot be replaced by snapshots and hold starts after final frame',()=>{const h=harness();h.run(setup);h.run("textFrames={text:'PLAIN',sources:[{id:'host',at:100}]};effectFrame='A';let remaining=['B','C'];effectSession={next:()=>remaining.shift(),free(){}};animationIndex=0;frameElapsed=0;lastEffect='decrypt';holdElapsed=0");assert.equal(h.run('effectFrame'),'A');h.run('observe(data,101000);advanceEffects(34)');assert.equal(h.run('effectFrame'),'B');h.run('advanceEffects(34)');assert.equal(h.run('effectFrame'),'C');assert.equal(h.run('holdElapsed'),0);h.run('advanceEffects(34)');assert.equal(h.run('animationIndex'),-1);assert.equal(h.run('holdElapsed'),0);h.run("snapshot.terminal_text='current';advanceEffects(9999)");assert.equal(h.run('loadingFrames'),false);h.run('advanceEffects(1)');assert.equal(h.run('loadingFrames'),true);});
test('hold defaults to 10 seconds and adjusts in one second increments',()=>{const h=harness();assert.equal(h.run('holdSeconds'),10);h.run('adjustHold(1)');assert.equal(h.run('holdSeconds'),11);h.run('adjustHold(-1)');assert.equal(h.run('holdSeconds'),10);h.run('adjustHold(-100)');assert.equal(h.run('holdSeconds'),0);});
test('paused and reduced motion freeze playback progression',()=>{for(const reduce of [false,true]){const h=harness(reduce);h.run(setup);h.run("textFrames={text:'PLAIN',frames:['A','B'],fps:30,sources:[{id:'host',at:100}]};animationIndex=0;paused="+!reduce);h.run('advanceEffects(5000)');assert.equal(h.run('animationIndex'),0);}});

test('fractional render ticks preserve animation timing',()=>{const h=harness();h.run(setup);h.run("textFrames={sources:[{id:'host',at:100}]};effectSession={next:()=>({}),free(){}};animationIndex=0;frameElapsed=0;for(let i=0;i<100;i++)advanceEffects(33.1)");assert.equal(h.run('animationIndex'),99);});

test('renderer errors and source loss release sessions and retain live state',()=>{for(const reason of ['failure','offline']){const h=harness();h.run(setup);h.run("let freed=0;effectSession={next(){throw Error()},free(){freed++}};textFrames={sources:[{id:'host'}]};animationIndex=0;frameElapsed=0");if(reason==='offline')h.run('disconnect()');h.run('advanceEffects(40)');assert.equal(h.run('freed'),1);assert.equal(h.run('animationIndex'),-1);}});
test('fixed effect colours follow the active palette and retain intensity',()=>{const h=harness();h.run("palette={background:'#101010',foreground:'#eeeeee',blue:'#ff8800',cyan:'#ff8800',green:'#88aa22',yellow:'#ddbb44',red:'#cc4433'}");assert.equal(h.run('themedColour(0, palette.background)'),'#101010');assert.equal(h.run('themedColour(0xffff8800, palette.foreground)'),'rgb(255,136,0)');assert.notEqual(h.run('themedColour(0xff00ff00, palette.foreground)'),'rgb(0,255,0)');});

test('denser terminal fills the viewport inside modest side padding',()=>{const h=harness();for(const [w,height] of [[1280,720],[1920,1080],[1536,864],[1000,800]]){const g=h.run(`geometry(${w},${height})`);assert.ok(g.margin>=20 && g.margin<=40);assert.ok(Math.abs(g.cell*140+g.margin*2-w)<.001);assert.ok(Math.abs(g.line*44+32-height)<.001);assert.ok(g.font<=g.line);}});
test('resize updates canvas backing size and the shared terminal dimensions',()=>{const h=harness();h.run('innerWidth=1920;innerHeight=1080;devicePixelRatio=2;resize()');assert.equal(h.get('scene').width,3840);assert.equal(h.get('scene').height,2160);assert.equal(h.run('width'),1920);assert.equal(h.run('height'),1080);h.run('innerWidth=1280;innerHeight=720;resize()');assert.equal(h.get('scene').width,2560);assert.equal(h.run('geometry(width,height).cell*140+geometry(width,height).margin*2'),1280);});

test('live rendering draws the rolling observations even with server terminal_text',()=>{const h=harness(false,true);h.run(setup);h.run("snapshot.terminal_text='STATIC SNAPSHOT';record('EXEC','idle -> working milestone',101000);draw(500)");assert.ok(h.get('scene').calls.map(c=>c[0]).join('').includes('idle -> working milestone'));assert.ok(h.run("sceneRows().join('\\n')").includes('[EXEC]'));});
test('feed movement follows arrivals and settles without inventing activity',()=>{const h=harness();h.run(setup);h.run('scrollDistance=0;performance.now=()=>1000;record("EXEC","transition",101000)');assert.equal(h.run('scrollOffset(999)'),1);assert.equal(h.run('scrollOffset(1000)'),1);assert.equal(h.run('scrollOffset(1130)'),.5);assert.equal(h.run('scrollOffset(1260)'),0);h.run('paused=true');assert.equal(h.run('scrollOffset(1000)'),0);});
test('sampled status transitions stamp once, baseline and revisions do not make banners',()=>{const h=harness();h.run(setup);assert.equal(h.run('stampCandidate'),null);h.run("data.hosts[0].agents[0].status='done';observe(data,101000);observe(data,102000)");assert.equal(h.run("records.filter(r=>r.kind==='DONE').length"),1);assert.equal(h.run('stampCandidate.kind'),'DONE');h.run('updateStamp(100)');assert.equal(h.run('activeStamp.kind'),'DONE');h.run("data.hosts[0].agents[0].status='blocked';observe(data,103000);updateStamp(101)");assert.equal(h.run('activeStamp'),null);h.run('updateStamp(30000)');assert.equal(h.run('activeStamp'),null);});
test('pending art expires, disappears on source loss and respects reduced motion',()=>{for(const reason of ['expired','lost','reduced']){const h=harness(reason==='reduced');h.run(setup);h.run("data.hosts[0].agents[0].status='blocked';observe(data,101000)");if(reason==='lost')h.run('disconnect()');h.run(`updateStamp(${reason==='expired'?30100:100})`);assert.equal(h.run('activeStamp'),null);}});
test('typed readiness and sequence changes are observations rather than invented transitions',()=>{const h=harness();h.run(setup);h.run("data.hosts[0].agents[0].technical={revision:1,state_change_seq:2,interactive_ready:false,launch_pending:true};observe(data,101000);data.hosts[0].agents[0].technical={revision:3,state_change_seq:4,interactive_ready:true,launch_pending:false};observe(data,102000);observe(data,103000)");assert.equal(h.run("records.filter(r=>r.kind==='STATESEQ').length"),1);assert.equal(h.run("records.filter(r=>r.kind==='READY').length"),1);assert.equal(h.run("records.filter(r=>r.kind==='LAUNCH').length"),1);assert.ok(h.run("records.find(r=>r.kind==='STATESEQ').text").includes('intermediate states not sampled'));});
test('effect capture includes the same current event feed as the live composition',()=>{const h=harness();h.run(setup);h.run("record('INPUT','working -> blocked',101000)");assert.ok(h.run("sceneRows().slice(31,41).join(' ')").includes('working -> blocked'));assert.equal(h.run('sceneRows().length'),44);assert.ok(h.run('sceneRows().every(row=>row.length<=140)'));});

test('effect captures use event text without activating or baking ephemeral artwork',()=>{const h=harness();h.run(setup);h.run("data.hosts[0].agents[0].status='done';observe(data,101000);const STAMP_ART={DONE:Array(9).fill('BANNER GLYPHS')}");assert.ok(!h.run("sceneRows(100,false).join(' ')").includes('BANNER GLYPHS'));assert.equal(h.run('activeStamp'),null);assert.equal(h.run('stampCandidate.kind'),'DONE');h.run('updateStamp(100)');assert.ok(!h.run("sceneRows(101,false).join(' ')").includes('BANNER GLYPHS'));assert.ok(h.run("sceneRows(101).join(' ')").includes('BANNER GLYPHS'));h.run('updateStamp(6100)');assert.equal(h.run('activeStamp'),null);});
