import test from 'node:test';
import assert from 'node:assert/strict';
import {allowanceView, relativeTime, createAllowancePanel} from '../web/allowances.mjs';
const now=1_800_000_000_000;
const sample={label:'Personal',plan:'pro',available:true,sampled_at:now/1000-60,weekly_remaining:26,weekly_resets_at:now/1000+90000,reset_count:1,reset_expires_at:now/1000+180000};
test('weekly and reset passes retain their separate meaning and relative times',()=>{const v=allowanceView(sample,{now});assert.equal(v.weekly,'26%');assert.equal(v.reset,'in 1d 1h');assert.equal(v.passes,'1');assert.equal(v.expiry,'in 2d 2h');assert.equal(v.status,'Checked 1m ago');});
test('missing and zero are distinct; unavailable source cannot look live',()=>{assert.equal(allowanceView({...sample,weekly_remaining:0,reset_count:0},{now}).weekly,'0%');assert.equal(allowanceView({...sample,reset_count:0},{now}).expiry,'None');for(const s of [{...sample,sampled_at:now/1000-601},{...sample,sampled_at:now/1000+1},{...sample,available:false}]){const v=allowanceView(s,{now});assert.equal(v.weekly,'—');assert.equal(v.passes,'—');}assert.equal(allowanceView(sample,{now,disconnected:true}).status,'Disconnected');});
test('scheduled reset passing never fabricates a refilled weekly allowance',()=>{assert.equal(allowanceView({...sample,weekly_resets_at:now/1000-1},{now}).weekly,'—');assert.equal(relativeTime(null,now),'Unknown');assert.equal(relativeTime(now/1000-600,now),'10m ago');});
test('invalid values cannot populate numeric instruments',()=>{const v=allowanceView({...sample,weekly_remaining:101,reset_count:-1,reset_expires_at:null},{now});assert.equal(v.weekly,'—');assert.equal(v.passes,'—');assert.equal(v.expiry,'Unknown');});
test('two persistent account panels update only when visible values change',()=>{let renders=0;const make=()=>({children:[],style:{},append(...xs){this.children.push(...xs);},setAttribute(){}});const root={ownerDocument:{createElement:make},replaceChildren(...xs){this.children=xs;renders++;}};const panel=createAllowancePanel({root});panel.update([sample],{now});assert.equal(root.children.length,2);panel.update([sample],{now});assert.equal(renders,1);panel.update([sample],{now:now+60000});assert.equal(renders,2);});

test('elapsed reset-pass expiry invalidates the old count without inventing zero',()=>{const v=allowanceView({...sample,reset_expires_at:now/1000-60},{now});assert.equal(v.passes,'—');assert.equal(v.expiry,'1m ago');});

test('native business plan names are readable without losing their tier',()=>{assert.equal(allowanceView({...sample,plan:'self_serve_business_prolite'},{now}).plan,'Business Pro Lite');});
test('weekly room and burn use only the reported allowance window',()=>{const activity={...sample,daily_usage:[{date:'2026-09-20',tokens:0},{date:'2026-09-22',tokens:9000}]};const view=allowanceView(activity,{now});assert.ok(Math.abs(view.roomPerDay-24.96)<1e-9);assert.ok(Math.abs(view.burnPerDay-74*86400000/(7*86400000-90000000))<1e-9);assert.equal(view.daily.length,2);assert.equal(view.daily[0].glyph,'▁');assert.equal(view.daily[1].glyph,'█');for(const changed of [{...activity,sampled_at:now/1000-601},{...activity,weekly_resets_at:now/1000-1},{...activity,weekly_resets_at:now/1000+8*86400}]){const invalid=allowanceView(changed,{now});assert.equal(invalid.roomPerDay,null);assert.equal(invalid.burnPerDay,null);}assert.equal(allowanceView({...activity,weekly_resets_at:now/1000+7*86400-1800},{now}).burnPerDay,null);assert.equal(allowanceView({...activity,daily_usage:[{date:'bad',tokens:1}]},{now}).daily,null);});
test('runway applies remaining allowance to observed burn, with unknown and zero distinct',()=>{const ten={...sample,weekly_remaining:10,weekly_resets_at:now/1000+3.25*86400};const v=allowanceView(ten,{now});assert.equal(v.runway,'~10h left');assert.ok(Math.abs(v.burnPerDay-24)<1e-9);assert.ok(Math.abs(v.roomPerDay-10/3.25)<1e-9);assert.equal(allowanceView({...ten,weekly_remaining:99},{now}).runway,'Beyond reset');assert.equal(allowanceView({...ten,weekly_remaining:0},{now}).runway,'0h left');assert.equal(allowanceView({...ten,sampled_at:now/1000-601},{now}).runway,'—');assert.equal(allowanceView({...ten,weekly_resets_at:now/1000+8*86400},{now}).runway,'—');});
test('account card connects remaining allowance to runway without daily token clutter',()=>{const make=(tag)=>({tag,children:[],style:{},attrs:{},textContent:'',append(...xs){this.children.push(...xs);},setAttribute(key,value){this.attrs[key]=value;}});const root={ownerDocument:{createElement:make},replaceChildren(...xs){this.children=xs;}};createAllowancePanel({root}).update([{...sample,weekly_remaining:10,weekly_resets_at:now/1000+3.25*86400,daily_usage:[{date:'2026-09-22',tokens:763322638}]}],{now});const card=root.children[0];const walk=node=>[node,...node.children.flatMap(walk)];const nodes=walk(card);assert.equal(card.attrs['data-pace'],'over');assert.ok(nodes.some(node=>node.className==='allowance-percent'&&node.textContent==='10%'));assert.ok(nodes.some(node=>node.className==='allowance-gauge'&&node.children[0].style.width==='10%'));assert.ok(nodes.some(node=>node.className==='allowance-outlook'&&node.children[1].textContent==='~10h left'));assert.ok(nodes.some(node=>node.className==='allowance-reset-time'&&node.textContent==='Reset in 3d 6h'));assert.equal(nodes.some(node=>String(node.textContent).includes('763,322,638')||node.textContent==='Daily tokens'),false);});
