import test from 'node:test';
import assert from 'node:assert/strict';
import {PixelField,musicEnergy,gridFor,ditherThreshold} from '../web/background.mjs';
function fixture(reduced=false){let calls=[];const motion={matches:reduced},environment={devicePixelRatio:3,document:{hidden:false},matchMedia:()=>motion,performance:{now:()=>1000}};const ctx={setTransform(){},clearRect(){calls=[];},fillRect(...args){calls.push([...args,this.fillStyle,this.globalAlpha]);}};const canvas={getContext:()=>ctx,getBoundingClientRect:()=>({width:1920,height:1080})};return {field:new PixelField(canvas,{environment}),canvas,environment,motion,calls:()=>calls};}
test('only current playing music supplies bounded measured energy',()=>{const music={state:'playing',captured_at:10,bands:[.2,2,-1,NaN]};assert.deepEqual(musicEnergy(music,11000,10500),[.2,1,0,0]);for(const state of ['paused','stopped','unknown'])assert.deepEqual(musicEnergy({...music,state},11000,10500),[]);assert.deepEqual(musicEnergy(music,14000,13500),[]);assert.deepEqual(musicEnergy(music,11000,7000),[]);assert.deepEqual(musicEnergy({...music,captured_at:12},11000,10500),[]);assert.equal(musicEnergy({...music,bands:Array(100).fill(.5)},11000,10500).length,64);});
test('grid remains bounded at 720p, 1080p and 4K; backing pixels cap DPR at two',()=>{for(const [w,h] of [[1280,720],[1920,1080],[3840,2160]]){const grid=gridFor(w,h);assert.ok(grid.columns*grid.rows<12250);}const {canvas}=fixture();assert.equal(canvas.width,3840);assert.equal(canvas.height,2160);assert.equal(new Set(Array.from({length:64},(_,i)=>ditherThreshold(i%8,Math.floor(i/8)))).size,64);});
test('hidden frames skip drawing and discard clicks; click storage is bounded',()=>{const f=fixture();for(let i=0;i<100;i++)f.field.click(20,20);assert.equal(f.field.impulses.length,4);f.environment.document.hidden=true;f.field.frame(1000);assert.equal(f.calls().length,0);assert.equal(f.field.impulses.length,0);f.field.click(20,20);assert.equal(f.field.impulses.length,0);});
test('reduced motion yields stationary pixels without music or click animation',()=>{const f=fixture(true);f.field.update({music:{state:'playing',captured_at:Date.now()/1000,bands:Array(16).fill(1)}});f.field.click(100,100);f.field.frame(1000);const first=f.calls().map(x=>[...x]);f.field.pointer(20,20);f.field.frame(2000);assert.deepEqual(f.calls(),first);assert.equal(f.field.impulses.length,0);});
test('theme, pointer and disposal work without touching card content',()=>{const f=fixture();f.field.update({colours:{accent:'#123456',background:'#fafafa',green:'invalid'}});f.field.pointer(50,50);f.field.frame(1000);assert.ok(f.calls().length);assert.ok(f.calls().every(c=>typeof c[4]==='string'));assert.equal(f.field.colours.accent,'#123456');const before=f.calls();f.field.frame(1010);assert.equal(f.calls(),before);f.field.dispose();f.field.frame(2000);assert.equal(f.calls().length,0);});

test('upstream noise and logo stamp create bounded, distinct field geometry',()=>{const f=fixture();f.field.frame(1000);const quiet=f.calls().map(c=>[...c]);f.field.click(500,400);f.field.frame(1040);assert.notDeepEqual(f.calls(),quiet);assert.equal(f.field.impulses[0].from,.45);assert.ok(f.field.impulses[0].life<.71);f.field.frame(2000);assert.equal(f.field.impulses.length,0);assert.equal(f.field.noise.length,128*128);assert.equal(f.field.jitter.length,64*64);assert.equal(f.field.bandsNow.length,32);});
test('ten measured bands interpolate to upstream columns and stale audio clears immediately',()=>{const f=fixture();f.field.update({music:{state:'playing',captured_at:Date.now()/1000,bands:Array(10).fill(.8)}});f.field.frame(1000);assert.ok(f.field.bandsNow.every(x=>x>.5));assert.equal(f.field.beatPulse,0);f.field.update({music:{state:'paused',captured_at:Date.now()/1000,bands:Array(10).fill(1)}});f.field.frame(1040);assert.ok(f.field.bandsNow.every(x=>x===0));assert.equal(f.field.beatPulse,0);});

test('all visualiser inks remain muted and derive from accent rather than green',()=>{for(const background of ['#000000','#ffffff']){const f=fixture();f.field.update({colours:{background,accent:'#ff0000',green:'#00ff00'},music:{state:'playing',captured_at:Date.now()/1000,bands:Array(10).fill(1)}});f.field.pointer(500,400);f.field.click(500,400);f.field.frame(1000);assert.ok(f.calls().length);for(const call of f.calls()){const rgb=call[4].match(/\d+/g).map(Number);assert.equal(rgb[1],rgb[2]);if(background==='#000000'){assert.ok(rgb[0]<=87);assert.equal(rgb[1],0);}else{assert.equal(rgb[0],255);assert.ok(rgb[1]>=168);}}}});
