import test from 'node:test';
import assert from 'node:assert/strict';
import {PixelField,musicEnergy,gridFor,ditherThreshold} from '../web/background.mjs';
function fixture(reduced=false){let calls=[];const motion={matches:reduced},environment={devicePixelRatio:3,document:{hidden:false},matchMedia:()=>motion,performance:{now:()=>1000}};const ctx={setTransform(){},clearRect(){calls=[];},fillRect(...args){calls.push([...args,this.fillStyle,this.globalAlpha]);}};const canvas={getContext:()=>ctx,getBoundingClientRect:()=>({width:1920,height:1080})};return {field:new PixelField(canvas,{environment}),canvas,environment,motion,calls:()=>calls};}
test('only current playing music supplies bounded measured energy',()=>{const music={state:'playing',captured_at:10,bands:[.2,2,-1,NaN]};assert.deepEqual(musicEnergy(music,11000,10500),[.2,1,0,0]);for(const state of ['paused','stopped','unknown'])assert.deepEqual(musicEnergy({...music,state},11000,10500),[]);assert.deepEqual(musicEnergy(music,14000,13500),[]);assert.deepEqual(musicEnergy(music,11000,7000),[]);assert.deepEqual(musicEnergy({...music,captured_at:12},11000,10500),[]);assert.equal(musicEnergy({...music,bands:Array(100).fill(.5)},11000,10500).length,64);});
test('grid remains bounded at 720p, 1080p and 4K; backing pixels cap DPR at two',()=>{for(const [w,h] of [[1280,720],[1920,1080],[3840,2160]]){const grid=gridFor(w,h);assert.ok(grid.columns*grid.rows<12250);}const {canvas}=fixture();assert.equal(canvas.width,3840);assert.equal(canvas.height,2160);assert.equal(new Set(Array.from({length:16},(_,i)=>ditherThreshold(i%4,Math.floor(i/4)))).size,16);});
test('hidden frames skip drawing and discard clicks; click storage is bounded',()=>{const f=fixture();for(let i=0;i<100;i++)f.field.click(20,20);assert.equal(f.field.impulses.length,6);f.environment.document.hidden=true;f.field.frame(1000);assert.equal(f.calls().length,0);assert.equal(f.field.impulses.length,0);f.field.click(20,20);assert.equal(f.field.impulses.length,0);});
test('reduced motion yields stationary pixels without music or click animation',()=>{const f=fixture(true);f.field.update({music:{state:'playing',captured_at:Date.now()/1000,bands:Array(16).fill(1)}});f.field.click(100,100);f.field.frame(1000);const first=f.calls().map(x=>[...x]);f.field.pointer(20,20);f.field.frame(2000);assert.deepEqual(f.calls(),first);assert.equal(f.field.impulses.length,0);});
test('theme, pointer and disposal work without touching card content',()=>{const f=fixture();f.field.update({colours:{accent:'#123456',background:'#fafafa',green:'invalid'}});f.field.pointer(50,50);f.field.frame(1000);assert.ok(f.calls().length);assert.ok(f.calls().every(c=>c[4]==='#123456'));const before=f.calls();f.field.frame(1010);assert.equal(f.calls(),before);f.field.dispose();f.field.frame(2000);assert.equal(f.calls().length,0);});
